## splog_setup
#-------------------------------------------------------------------------------
# level is optional for both sinks and loggers
# level for error logging is 'err', not 'error'
# _st => single threaded, _mt => multi threaded
# syslog_sink is automatically thread-safe by default, no need for _mt suffix

# max_size supports suffix
# - T (terabyte)
# - G (gigabyte)
# - M (megabyte)
# - K (kilobyte)
# - or simply no suffix (byte)

## Patterns (how the logger output is formatted)
#-------------------------------------------------------------------------------
# Documentation on changing the logger pattern:
# (https://github.com/gabime/spdlog/wiki/3.-Custom-formatting):
# global_pattern = "[%Y-%m-%dT%T%z] [%L] <%n>: %v"

[[pattern]]
name = "succient"
value = "[%T:%e][%^%L%$] %v"

## Sinks (where the loggers output to)
#-------------------------------------------------------------------------------

# Console sink
[[sink]]
name = "console"
type = "color_stdout_sink_mt"
level = "debug"

# File sink (the file gets created upon configuration)
[[sink]]
name = "file"
type = "rotating_file_sink_mt"
base_filename = "edie.log"
max_size = "5M"
max_files = 2
level = "debug"

## Loggers (where the program writes to)
#-------------------------------------------------------------------------------

# Root logger (the root logger is required, but its configuration can be 
#              modified. For example, the "file" sink could be removed)
[[logger]]
name = "root"
sinks = [
    "console",
    "file" ]
level = "debug"
# pattern = "succient"
