[project]
name = "novatel_edie_install_customizer"
description = "Tool for creating a custom installation of novatel_edie package"
version = "3.2.27"
license = {text = "MIT"}
requires-python = ">=3.8"
dependencies = [
    "novatel_edie",
]
