# The Python workflow to run on merges or pushes to most branches.
name: Python Basic

on:
  push:
    branches-ignore:
      - main
      - dev-riley-kinahan-github-action-improvements
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'resources/**'
jobs:
  build:
    uses: ./.github/workflows/build_python.yml
