# The basic workflow to run on most branches
name: Basic

on:
  push:
    branches-ignore:
      - main
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'resources/**'
jobs:
  build-python:
    uses: ./.github/workflows/build_python.yml
    with:
        python_versions: cp39* cp310* cp311* cp312*
  build-cpp:
    uses: ./.github/workflows/build_cpp.yml
