# The C++ workflow to run on merges or pushes to most branches.
name: C++ Basic

on:
  push:
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'resources/**'
    branches:
      -main
jobs:
  build:
    uses: ./.github/workflows/build_cpp.yml
