name: Benchmark Comparison

on:
  workflow_call:

jobs:
  benchmark-comparison:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build g++ jq bc

      - name: Install Conan
        uses: turtlebrowser/get-conan@main

      - name: Install CMake
        uses: lukka/get-cmake@latest

      - name: Build main branch
        run: |
          cmake -S . -B build-main -DCMAKE_BUILD_TYPE=Release -G Ninja -DBUILD_BENCHMARKS=ON -DBUILD_TESTS=OFF -DBUILD_EXAMPLES=OFF
          cmake --build build-main --parallel --config Release

      - name: Run main branch benchmarks
        run: ./build-main/bin/linux-x86_64-gnu-Release/benchmark --benchmark_format=json | tail -n +2 > main_benchmark.json

      - name: Save main benchmark JSON
        run: cp main_benchmark.json /tmp/main_benchmark.json

      - name: Checkout current branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref }}
          fetch-depth: 0

      - name: Restore main benchmark JSON
        run: cp /tmp/main_benchmark.json main_benchmark.json

      - name: Build current branch
        run: |
          cmake -S . -B build-current -DCMAKE_BUILD_TYPE=Release -G Ninja -DBUILD_BENCHMARKS=ON -DBUILD_TESTS=OFF -DBUILD_EXAMPLES=OFF
          cmake --build build-current --parallel --config Release

      - name: Run current branch benchmarks
        run: ./build-current/bin/linux-x86_64-gnu-Release/benchmark --benchmark_format=json | tail -n +2 > current_benchmark.json

      - name: Compare benchmarks
        run: python3 scripts/compare_benchmarks.py
        continue-on-error: true

