# A reusable workflow for building and testing the Python package.
name: Python Build

on:
  workflow_call:

jobs:
  build:
    name: Python - ${{ matrix.platform[0] }} - ${{ matrix.platform[2] }}
    runs-on: ${{ matrix.platform[1] }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - [Linux, ubuntu-latest, x86_64]
          # - [Linux, ubuntu-latest, i686]
          - [Windows, windows-latest, AMD64]
          # - [Windows, windows-latest, x86]
          # - [Windows, windows-latest, ARM64]
          # - [MacOS, macos-latest, x86_64]
          - [MacOS, macos-latest, arm64]
          # spdlog fails to build with the correct architecture on universal2
          # - [MacOS, macos-latest, universal2]
          # aarch64 with QEMU likely works, but builds 10x slower than the rest
          # - [Linux, ubuntu-latest, aarch64]
          # ppc64le is too obscure and slow to build due to emulation
          # - [Linux, ubuntu-latest, ppc64le]
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # - name: Install cibuildwheel
      #   run: python -m pip install --upgrade cibuildwheel

      # - name: Build wheels
      #   run: python -m cibuildwheel --output-dir wheelhouse
      #   env:
      #     CIBW_ARCHS: ${{ matrix.platform[2] }}
      #     CIBW_BUILD: cp39* cp312*
      #     CIBW_SKIP: "*-musllinux*"

        
      - name: Create files
        run: |
          mkdir wheelhouse
          touch wheelhouse/file1.txt
          touch wheelhouse/file2.txt

      - name: Inspect
        run: ls wheelhouse/

      - name: Store build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform[0] }}-${{ matrix.platform[2] }}-wheels
          path: wheelhouse/
