# A reusable workflow for building and testing the Python package.
name: Python Build

on:
  workflow_call:
    inputs:
      python_versions:
        description: 'Which versions to build wheels for'
        required: false
        default: cp313*
        type: string


jobs:
  build:
    name: Python - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: Linux
            runs-on: ubuntu-latest
            arch: x86_64
          - os: Linux
            runs-on: ubuntu-24.04-arm
            arch: aarch64
          - os: Windows
            runs-on: windows-latest
            arch: x86
          - os: Windows
            runs-on: windows-latest
            arch: AMD64
          # Windows ARM64 is cross-compiled, but stubgen.py fails due to a missing native interpreter
          # - os: Windows
          #   runs-on: windows-latest
          #   arch: ARM64
          - os: macOS
            runs-on: macos-13
            arch: x86_64
          - os: macOS
            runs-on: macos-latest
            arch: arm64
          - os: macOS
            runs-on: macos-latest
            arch: universal2
    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.23.2
        env:
          CIBW_ARCHS: ${{ matrix.arch }}
          CIBW_BUILD: ${{ inputs.python_versions }}
          CIBW_SKIP: "*-musllinux*"

      - name: Inspect
        run: ls wheelhouse/

      - name: Store build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ matrix.arch }}-${{ strategy.job-index }}
          path: wheelhouse/
