# The workflow to run on merges or pushes to the main branch.
name: Main

on:
  push:
    branches:
      - main
      - dev-riley-kinahan-github-action-improvements
jobs:
  build-python:
    uses: ./.github/workflows/build_python.yml
  build-cpp:
    uses: ./.github/workflows/build_cpp.yml

  increment-version:
    runs-on: ubuntu-latest
    needs: [build-python, build-cpp]
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Get Pull Request Info
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            commit_sha=$(git rev-parse HEAD)
            pr_info=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/commits/$commit_sha/pulls" \
            | jq '.[0]')

            if [ "$pr_info" == "null" ]; then
            echo "No pull request found for commit $commit_sha"
            echo "VERSION_TYPE=patch" >> $GITHUB_ENV

            exit 0
            fi

            echo "Pull Request Number: $(echo $pr_info | jq '.number')"
            echo "Title: $(echo $pr_info | jq '.title')"
            echo "Merged By: $(echo $pr_info | jq '.user.login')"
            pr_number=$(echo $pr_info | jq '.number')
            pr_tags=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/issues/$pr_number/labels" \
            | jq -r '.[].name')
            echo "Tags: $pr_tags"

            if echo "$pr_tags" | grep -q "major"; then
              VERSION_TYPE=major
            elif echo "$pr_tags" | grep -q "minor"; then
              VERSION_TYPE=minor
            else
              VERSION_TYPE=patch
            fi

            echo "VERSION_TYPE=$VERSION_TYPE"
            echo "VERSION_TYPE=$VERSION_TYPE" >> $GITHUB_ENV

      - name: Bump Python version
        id: bump
        uses: callowayproject/bump-my-version@master
        env:
          BUMPVERSION_TAG: "true"
        with:
          args: "${{ env.VERSION_TYPE }}"
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Bump C++ version
        run: |
          sed -i 's/project(\(.*\) VERSION [0-9]*\.[0-9]*\.[0-9]*)/project(\1 VERSION ${{ steps.bump.outputs.current-version }})/' CMakeLists.txt

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add CMakeLists.txt
          git commit -m "Bump version: ${{ steps.bump.outputs.current-version }} → ${{ steps.bump.outputs.current-version }}"
          git push origin main

      - name: Check
        if: steps.bump.outputs.bumped == 'true'
        run: |
          echo "Version was bumped from ${{ steps.bump.outputs.previous-version }} to ${{ steps.bump.outputs.current-version }}!"
