name: Test Python
on:
  push:
    branches-ignore:
      - main
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'resources/**'
jobs:
  build:
    uses: ./.github/workflows/build_python.yml
    with:
        python_versions: cp313*
        build_matrix: '[ ["Linux","ubuntu-latest","x86_64"], ["Windows","windows-latest","AMD64"], ["Linux", "ubuntu-latest", "aarch64"] ]'
