# Workflow for releasing a Python package to PyPI based on the current repository.
name: Release Python
on:
  workflow_dispatch:
jobs:
  build:
    uses: ./.github/workflows/build_python.yml
  publish:
    name: Publish release to PyPI
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: testpypi
      url: https://test.pypi.org/p/novatel-edie
    permissions:
      id-token: write
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: wheels
          path: wheelhouse/
      - name: Upload to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          verbose: true
          packages-dir: wheelhouse/
