name: Bump version

on:
  push:
  workflow_dispatch:
    # inputs:
    #   bump-type:
    #     description: 'Bump type'
    #     required: true
    #     default: 'patch'
    #     type: choice
    #     options:
    #     - major
    #     - minor
    #     - patch

jobs:
  get-pr-info:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Get Pull Request Info
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          commit_sha=$(git rev-parse HEAD)
          pr_info=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/commits/$commit_sha/pulls" \
            | jq '.[0]')
          echo "Pull Request Number: $(echo $pr_info | jq '.number')"
          echo "Title: $(echo $pr_info | jq '.title')"
          echo "Merged By: $(echo $pr_info | jq '.user.login')"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Bump version
        id: bump
        uses: callowayproject/bump-my-version@master
        env:
          BUMPVERSION_TAG: "true"
        with:
          args: "patch"
          github-token: ${{ secrets.GH_TOKEN }}

      - name: Check
        if: steps.bump.outputs.bumped == 'true'
        run: |
          echo "Version was bumped from ${{ steps.bump.outputs.previous-version }} to ${{ steps.bump.outputs.current-version }}!"
